# Generated by Django 4.1.7 on 2025-02-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_transportitem_cargoitem_alter_cargoorder_cargo_item_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportitem',
            name='carrier',
        ),
        migrations.DeleteModel(
            name='CargoItem',
        ),
        migrations.DeleteModel(
            name='TransportItem',
        ),
    ]
