# Generated by Django 4.1.7 on 2025-02-25 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CargoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loading_points', models.JSONField(default=list, help_text='List of loading points with city, address and post code')),
                ('unloading_points', models.JSONField(default=list, help_text='List of unloading points with city, address and post code')),
                ('insurance', models.BooleanField(default=False, help_text='Cargo Insurance')),
                ('trailer_type', models.CharField(blank=True, choices=[('tautliner', 'Tautliner'), ('reefer', 'Reefer'), ('insulated trailer', 'Insulated Trailer'), ('container chassis', 'Container chassis'), ('flatbed trailer', 'Flatbed trailer'), ('tandem trailer', 'Tandem trailer'), ('car transporter', 'Car transporter'), ('cattle trailer', 'Cattle trailer'), ('open-top trailer', 'Open-top trailer'), ('cement tanker', 'Cememnt tanker'), ('adr', 'ADR'), ('timber trailer', 'Timber trailer'), ('lowboy trailer', 'Lowboy trailer'), ('tanker trailer', 'Tanker trailer'), ('dump trailer', 'Dump trailer'), ('bulk flour tanker', 'Bulk flour tanker')], help_text='Required trailer type', max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PDF-file CMR', upload_to='cmr_documents/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique number of contract', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Freight cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_deadline', models.DateTimeField(help_text='Deadline of payment')),
                ('delivery_deadline', models.DateTimeField(help_text='Delivery dealine')),
                ('accepted', models.BooleanField(default=False, help_text='The contract was accepted by both parties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.BooleanField(default=False, help_text='Cargo Insurance')),
                ('loading_points', models.JSONField(default=list, help_text='List of loading points with city, address and post code')),
                ('unloading_points', models.JSONField(default=list, help_text='List of unloading points with city, address and post code')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
