# Generated by Django 4.1.7 on 2025-02-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cargoitem'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.virtualwarehouse'),
        ),
        migrations.AddField(
            model_name='virtualwarehouse',
            name='items',
            field=models.ManyToManyField(through='orders.WarehouseStock', to='users.cargoitem'),
        ),
        migrations.AddField(
            model_name='virtualwarehouse',
            name='shipper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='users.shipperprofile'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_orders', to='users.carrierprofile'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='transport_orders', to='orders.transportcategory'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='transport_items',
            field=models.ManyToManyField(related_name='transport_orders', to='users.transportitem'),
        ),
        migrations.AddIndex(
            model_name='transportcategory',
            index=models.Index(fields=['name'], name='orders_tran_name_10f1a5_idx'),
        ),
        migrations.AddField(
            model_name='shipmentcontract',
            name='cargo_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='orders.cargoorder'),
        ),
        migrations.AddField(
            model_name='shipmentcontract',
            name='transport_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='orders.transportorder'),
        ),
        migrations.AddField(
            model_name='cmrdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_documents', to='orders.shipmentcontract'),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='cargo_item',
            field=models.ManyToManyField(related_name='cargo_orders', to='users.cargoitem'),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cargo_orders', to='orders.cargocategory'),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_orders', to='users.shipperprofile'),
        ),
        migrations.AddIndex(
            model_name='cargocategory',
            index=models.Index(fields=['name'], name='orders_carg_name_3a467e_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['-created_at'], name='orders_tran_created_80b022_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['-updated_at'], name='orders_tran_updated_be650a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentcontract',
            index=models.Index(fields=['-created_at'], name='orders_ship_created_4d9404_idx'),
        ),
        migrations.AddIndex(
            model_name='cmrdocument',
            index=models.Index(fields=['-generated_at'], name='orders_cmrd_generat_665761_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoorder',
            index=models.Index(fields=['-created_at'], name='orders_carg_created_116183_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoorder',
            index=models.Index(fields=['-updated_at'], name='orders_carg_updated_a6e4dc_idx'),
        ),
    ]
