# Generated by Django 4.1.7 on 2025-02-26 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(help_text='Driver license number', max_length=20, unique=True)),
                ('truck_number', models.CharField(help_text='Truck license plate', max_length=20, unique=True)),
                ('trailer_number', models.CharField(help_text='Trailer license plate', max_length=20, unique=True)),
                ('trailer_type', models.CharField(choices=[('tautliner', 'Tautliner'), ('reefer', 'Reefer'), ('insulated trailer', 'Insulated Trailer'), ('container chassis', 'Container chassis'), ('flatbed trailer', 'Flatbed trailer'), ('tandem trailer', 'Tandem trailer'), ('car transporter', 'Car transporter'), ('cattle trailer', 'Cattle trailer'), ('open-top trailer', 'Open-top trailer'), ('cement tanker', 'Cememnt tanker'), ('adr', 'ADR'), ('timber trailer', 'Timber trailer'), ('lowboy trailer', 'Lowboy trailer'), ('tanker trailer', 'Tanker trailer'), ('dump trailer', 'Dump trailer'), ('bulk flour tanker', 'Bulk flour tanker')], help_text='Type of trailer', max_length=50)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_items', to='users.carrierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cargo name', max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Available volume in (m³)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Total weight in (kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('on_pallets', models.BooleanField(default=False, help_text='Stored on pallets')),
                ('number_of_pallets', models.PositiveIntegerField(default=0, help_text='Number of pallets')),
                ('packaging', models.CharField(blank=True, help_text='Packaging type (e.g, boxes, barrels)', max_length=255, null=True)),
                ('storage_conditions', models.TextField(blank=True, help_text='Special storage conditions', null=True)),
                ('transport_conditions', models.TextField(blank=True, help_text='Required transport conditions', null=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='users.shipperprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='cargo_item',
            field=models.ManyToManyField(related_name='cargo_orders', to='orders.cargoitem'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='transport_items',
            field=models.ManyToManyField(related_name='transport_orders', to='orders.transportitem'),
        ),
        migrations.AlterField(
            model_name='virtualwarehouse',
            name='items',
            field=models.ManyToManyField(through='orders.WarehouseStock', to='orders.cargoitem'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cargoitem'),
        ),
    ]
