# Generated by Django 4.1.7 on 2025-02-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_transportitem_carrier_delete_cargoitem_and_more'),
        ('orders', '0003_transportitem_cargoitem_alter_cargoorder_cargo_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoorder',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='users.carrierprofile'),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
