# Generated by Django 4.1.7 on 2025-03-01 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cargoorder_carrier_cargoorder_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight cost', max_digits=10, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
