# Generated by Django 4.1.7 on 2025-03-02 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cargoorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight cost', max_digits=10, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
