# Generated by Django 4.1.7 on 2025-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_transportorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoorder',
            name='route_info',
            field=models.JSONField(blank=True, help_text='Информация о маршруте (расстояние, время, геометрия)', null=True),
        ),
    ]
